### ISSUE TITLE
4 population analysis

### ISSUE THREAD

**Issue by tangerzhang** [joanam/scripts#2]
Hi,
Thanks for providing a nice program.
I am wondering is it possible to use your program (HaploABBABABA_multithreaded.jar) for 4 population analysis?

**Comment by joanam** [comment]
Dear Zhang
Yes, it is possible. However, I am currently revising the software and until then it may be better to use AdmixTools: https://github.com/DReichLab/AdmixTools 
Cheers,
Joana
