### ISSUE TITLE
convertVCFtoEigenstrat.sh: incompatibility with non-standard VCF file

### ISSUE THREAD

**Issue by Marvin02860** [joanam/scripts#3]
Hello Joana,
I would like to use the script **convertVCFtoEigenstrat.sh**  but I have the following issues:

The VCF file I am using contains chromosome names that are not standard, looking like this: ctg7180000255172 (I have 260 different names looking like this) and this seems to be a problem for the script to work, as I get the message back: 
_fatalx:
bad chrom: ctg7180000255172
Aborted (core dumped)_
As a result, the .eigenstratgeno file is not created, and neither are the other files (needed for working with AdmixTools).

First, I tried to come up with the solution of replacing all my "chromosome" names into standard number from 1 to 260 in my VCF file. But again, it only works if I go up to 100 and will not accept numbers beyond 100. So, as a last trial, I replaced all the names by "1". 
But then the next problem comes from the ID column of the VCF file: this column also contains the "ctg7180000255172" and it leads to the same problem. I do not want to lose this precious information for later on, so I don't know what to do anymore.

Would you have any suggestion regarding this issue?
Also, could there be a way to adapt the script so that we can force it to accept non-standard names?

Thank you for your help (any help will be appreciated:))
and thank you for sharing your useful scripts! 

All the best,
Marvin

**Comment by joanam** [comment]
Dear Marvin,
I hope you have now managed to convert your vcf file, if not, please use this version: 
https://github.com/speciationgenomics/scripts/blob/master/convertVCFtoEigenstrat.sh
Best,
Joana
