### ISSUE TITLE
convertVCFtoEigenstrat.sh:  no valid snps

### ISSUE THREAD

**Issue by XiaXiaTianTian** [joanam/scripts#6]
Hi, Joana,

It is very convenient to use this script to convert vcf to admixtools needed format. But I got an error. Could it be wrong parameters I use ? I only got 4 files,
 test.ld.renamedScaff.vcf.gz
 test.ld.map
 test.ld.ped
 par.PED.EIGENSTRAT. test.ld
but  test.ld.snp is zero.

sh convertVCFtoEigenstrat.sh test.ld.vcf.gz --renameScaff
 
VCFtools - 0.1.16
(C) Adam Auton and Anthony Marcketta 2009

Parameters as interpreted:
	--gzvcf test.ld.vcf.gz
	--mac 1
	--max-alleles 2
	--out test.ld
	--plink
	--remove-indels

Using zlib version: 1.2.11
Warning: Expected at least 2 parts in INFO entry: ID=PR,Number=0,Type=Flag,Description="Provisional reference allele, may not be based on real reference genome">
After filtering, kept 11 out of 11 Individuals
Writing PLINK PED and MAP files ... 
Done.
After filtering, kept 43374 out of a possible 43374 Sites
Run Time = 222.00 seconds
fatalx:
no valid snps
/ds3200_1/users_root/scripts-master_speciationgenomics/convertVCFtoEigenstrat.sh: line 129: 32372 Aborted                 (core dumped) convertf -p par.PED.EIGENSTRAT.${file}

Best,
Xia

**Comment by joanam** [comment]
Dear Xia,

I do not know what the problem is. Can you perhaps send me a subset of your vcf file to test if it is a bug or something specific with your vcf file? My email is joana<dot>isabel<dot>meier<at>gmail.com.

Best,
Joana

**Comment by jackzhong1995** [comment]
> Hi, Joana,
> 
> It is very convenient to use this script to convert vcf to admixtools needed format. But I got an error. Could it be wrong parameters I use ? I only got 4 files, test.ld.renamedScaff.vcf.gz test.ld.map test.ld.ped par.PED.EIGENSTRAT. test.ld but test.ld.snp is zero.
> 
> sh convertVCFtoEigenstrat.sh test.ld.vcf.gz --renameScaff
> 
> VCFtools - 0.1.16 (C) Adam Auton and Anthony Marcketta 2009
> 
> Parameters as interpreted: --gzvcf test.ld.vcf.gz --mac 1 --max-alleles 2 --out test.ld --plink --remove-indels
> 
> Using zlib version: 1.2.11 Warning: Expected at least 2 parts in INFO entry: ID=PR,Number=0,Type=Flag,Description="Provisional reference allele, may not be based on real reference genome"> After filtering, kept 11 out of 11 Individuals Writing PLINK PED and MAP files ... Done. After filtering, kept 43374 out of a possible 43374 Sites Run Time = 222.00 seconds fatalx: no valid snps /ds3200_1/users_root/scripts-master_speciationgenomics/convertVCFtoEigenstrat.sh: line 129: 32372 Aborted (core dumped) convertf -p par.PED.EIGENSTRAT.${file}
> 
> Best, Xia

hi，just check your chr id in your .map file

**Comment by he0811** [comment]
> Hi, Joana,
> 
> It is very convenient to use this script to convert vcf to admixtools needed format. But I got an error. Could it be wrong parameters I use ? I only got 4 files, test.ld.renamedScaff.vcf.gz test.ld.map test.ld.ped par.PED.EIGENSTRAT. test.ld but test.ld.snp is zero.
> 
> sh convertVCFtoEigenstrat.sh test.ld.vcf.gz --renameScaff
> 
> VCFtools - 0.1.16 (C) Adam Auton and Anthony Marcketta 2009
> 
> Parameters as interpreted: --gzvcf test.ld.vcf.gz --mac 1 --max-alleles 2 --out test.ld --plink --remove-indels
> 
> Using zlib version: 1.2.11 Warning: Expected at least 2 parts in INFO entry: ID=PR,Number=0,Type=Flag,Description="Provisional reference allele, may not be based on real reference genome"> After filtering, kept 11 out of 11 Individuals Writing PLINK PED and MAP files ... Done. After filtering, kept 43374 out of a possible 43374 Sites Run Time = 222.00 seconds fatalx: no valid snps /ds3200_1/users_root/scripts-master_speciationgenomics/convertVCFtoEigenstrat.sh: line 129: 32372 Aborted (core dumped) convertf -p par.PED.EIGENSTRAT.${file}
> 
> Best, Xia

Hi，Xia,
I encountered the same problem as you. I was wondering how you eventually resolved it. Can you please share?

Best Regards,
He
