### ISSUE TITLE
Errors in allelicbalance.py

### ISSUE THREAD

**Issue by ZuyaoLiu** [joanam/scripts#7]
Hi @joanam ,

I found two errors in the script allelicbalance.py.
1.  line 107 and 119:  if reads[0]>reads[1]:  should be  if int(reads[0])> Int(reads[1]):
2. between line 122 and 123: missing a  "result.append(":".join(genotype))"

 Best,
Zuyao

**Comment by joanam** [comment]
Many thanks for pointing these out. They have now been corrected.

Best wishes,
Joana
